variables:
  APPNAME: pallaviBBReviews
  
image: node:10.15

stages:
  - build
  - test
  - deploy

test:
  stage: test
  cache:
    paths:
      - bin/
  script:
  - npm i
  - npm test

deploy:
  image: pivotalpa/cf-cli-resource
  stage: deploy
  script:
  - cf login -a "https://api.cf.eu10.hana.ondemand.com"
  - cf push -f mta.yaml bb-reviews-starter-db --no-start
  - cf bs bb-reviews-starter-db bb-reviews-starter-db-hdi-container
  - cf start bb-reviews-starter-db
  - cf push -f mta.yaml pvd-bb-reviews-starter-srv --no-start
  - cf bs pvd-bb-reviews-starter-srv bb-reviews-starter-db-hdi-container
  - cf bs pvd-bb-reviews-starter-srv bb-reviews-starter-uaa
  - cf bs pvd-bb-reviews-starter-srv bb-reviews-starter-autoscaler -c scaling-rules.json
  - cf start bb-reviews-starter-srv
