version: '3'
services:
  web:
    image: "petertan/bb-reviewer"
    ports:
      - "4004:4004"
    volumes:
      - ${PWD}/default-env.json:/data/default-env.json
  srv:
    image: "deadbacon/bb-starter"
    ports:
      - "4000:4000"
